vich_uploader:
    db_driver: orm

    mappings:
        profil_photos:
            uri_prefix: '%profil_photos%'
            upload_destination: '%kernel.project_dir%/public%profil_photos%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
